### ISSUE TITLE
git clone https://github.com/nimiq/nimiq.git --recursive error

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [nimiq/nimiq#1]
fatal: clone of 'git@github.com:nimiq/x-element.git' into submodule path 'C:/Users/clark/git/nimiq/library/x-element' failed
Failed to clone 'library/x-element'. Retry scheduled
Cloning into 'C:/Users/clark/git/nimiq/apps/net-exchange-tool'...
Host key verification failed.
fatal: Could not read from remote repository.

**Comment by danimoh** [comment]
Hi xiaoming. This problem is not reproducible for me.
Could you please provide more information? (operating system, git client, etc.)

**Comment by xiaomingfuckeasylife** [comment]
thanks danimoh. now it is working . i add ssh to my github account then everything works fine. 
[https://stackoverflow.com/questions/25957125/git-submodule-permission-denied](url)
